version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: urlshortener
    ports:
      - 5432:5432
  mysql:
    image: mysql
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: securePassword
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: urlshortener
    ports:
      - 3306:3306