version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: urlshortener
    ports:
      - 5432:5432